image:
  - Visual Studio 2019
  - macOS
  - Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 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

install:
  - pip install -r requirements.txt

build_script:
  - flet pack main.py --name StrataGenAi --icon icon.png --product-name StrataGenAi --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc." --add-data "assets;assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

for:
  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf StrataGenAi-linux.tar.gz -C dist StrataGenAi

    artifacts:
      - path: StrataGenAi-linux.tar.gz

  #
  #   Windows package
  #
  - matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a StrataGenAi-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: StrataGenAi-windows.zip

  #
  #   macOS package
  #
  - matrix:
      only:
        - image: macOS

    after_build:
      - tar -czvf StrataGenAi-macos.tar.gz -C dist StrataGenAi.app

    artifacts:
      - path: StrataGenAi-macos.tar.gz
